### ISSUE TITLE
Widget pour de la documentation type API

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr-documentation#2]
Documenter des appels à des API de façon à décrire les requêtes et les réponses.

Ces éléments peuvent concerner une seule requête, insérée dans une documentation plus large de type article.

## Exemple de rendu : 
![image](https://github.com/IGNF/cartes-gouv-documentation/assets/28899274/50784c93-4cbe-4a0b-93ae-c877fd2dd92e)

Ce rendu est basé sur les admonition collapsible de material https://squidfunk.github.io/mkdocs-material/reference/admonitions/
Avec un peu de personnalisation pour les verbes API, leur donner une apparence swagger-ui-like.

**Comment by slafayIGN** [comment]
L'url à copier dans l'en-tête du composant accordéon (comme dans le titre du composant admonition) pose problème pour être copier.

Une nouvelle suggestion consiste à :
* afficher l'url dans un bloc de code
* afficher le reste des détails (éventuels corps de requête et de réponse) dans un accordéon)

Ainsi les URL avec ou sans détails ont la même allure et sont copiables et les contenus code des détails ne prennent pas beaucoup de place dans la page. Le fonctionnement en 2 onglets (quand il y a requête ET réponse) est abandonné.

**Comment by marionLX** [comment]
top! c'est bien compatible accessibilité?
