### ISSUE TITLE
Publier une image /documentation

### ISSUE THREAD

**Issue by slafayIGN** [IGNF/cartes.gouv.fr-documentation#57]
Publier l'image docker en mettant le site sur `/documentation` au lieu de la racine pour que ça corresponde à l'emplacement final du déploiement sur `cartes.gouv.fr/documentation`.

**Comment by ocruze** [comment]
Bon, j'ai réussi à publier l'image sur /documentation. Mais parfois quand on clique sur un lien qui ne finit pas par un "/", quelque chose se passe mal côté mut-dev et un port apparaît dans l'url, et donc le site ne marche plus. A contrôler.
